### ISSUE TITLE
Driver does not work on multiple versions of Linux

### ISSUE THREAD

**Issue by joeytroy** [nelullc/rollo-cups-driver#1]
I have been working with Rollo support and can not get the driver to work on Debian 12, Ubuntu 22.04LTS, or Ubuntu 24.04LTS. If I compile from the source code and then install the driver using the *.ppd through the CUPS web page it does not work. Nor does using the *.deb file.

If I use `lsusb` it does not show the device listed with either driver. I have attached the error logs from Ubuntu 22.04 and 24.04.
[error_log.zip](https://github.com/nelullc/rollo-cups-driver/files/15263392/error_log.zip)

**Comment by michaelrsweet** [comment]
Can you attach the output from the following commands?

```
lsusb -v
lpinfo -v
```

**Comment by michaelrsweet** [comment]
Oh, and FWIW I don't see any errors in the logs...

**Comment by joeytroy** [comment]
@michaelrsweet here is the commands run. Let me know if you need anything else. I am currently running Ubuntu 24.04LTS

[commands.zip](https://github.com/nelullc/rollo-cups-driver/files/15278335/commands.zip)

**Comment by michaelrsweet** [comment]
I think I have the issue fixed:

[main 1efb2ad] Fix dither buffer size (Issue #1)

**Comment by michaelrsweet** [comment]
OK, I've posted a source tarball and the various binaries packages.
